package subagent

import (
	"errors"
	"time"

	"github.com/mistakeknot/Skaffen/internal/agentloop"
	"github.com/mistakeknot/Skaffen/internal/provider"
)

// SubagentType defines a type of subagent (e.g., "explore", "general").
type SubagentType struct {
	Name         string   `toml:"name"`
	Description  string   `toml:"description"`
	Tools        []string `toml:"tools"`         // tool whitelist (empty = all)
	SystemPrompt string   `toml:"system_prompt"` // template with {{.TaskPrompt}}, {{.InjectedContext}}
	MaxTurns     int      `toml:"max_turns"`     // 0 = default (25)
	TokenBudget  int      `toml:"token_budget"`  // 0 = inherit from parent
	ReadOnly     bool     `toml:"read_only"`     // skip Intercore reservation
	Model           string   `toml:"model"`            // empty = inherit from parent
	Timeout         Duration `toml:"timeout"`          // 0 = default (120s)
	ContextTokenCap int      `toml:"context_token_cap"` // 0 = DefaultContextTokenCap
}

// Duration wraps time.Duration for TOML unmarshaling.
type Duration struct{ time.Duration }

func (d *Duration) UnmarshalText(text []byte) error {
	var err error
	d.Duration, err = time.ParseDuration(string(text))
	return err
}

// Validate checks required fields and applies defaults.
func (st *SubagentType) Validate() error {
	if st.Name == "" {
		return errors.New("subagent type: name is required")
	}
	if st.MaxTurns == 0 {
		st.MaxTurns = 25
	}
	if st.Timeout.Duration == 0 {
		st.Timeout.Duration = 120 * time.Second
	}
	return nil
}

// SubagentStatus represents the current state of a running subagent.
type SubagentStatus int

const (
	StatusPending SubagentStatus = iota
	StatusRunning
	StatusDone
	StatusFailed
)

func (s SubagentStatus) String() string {
	switch s {
	case StatusPending:
		return "pending"
	case StatusRunning:
		return "running"
	case StatusDone:
		return "done"
	case StatusFailed:
		return "failed"
	default:
		return "unknown"
	}
}

// SubagentTask is the input for spawning a subagent.
type SubagentTask struct {
	ID              string   // unique identifier (generated by runner)
	Type            string   // subagent type name (must exist in registry)
	Prompt          string   // task-specific prompt
	Description     string   // short label (3-5 words) for TUI display
	InjectedContext string   // optional context from parent
	BeadDescription string   // optional bead description for domain awareness
	FilePatterns    []string // glob patterns for Intercore reservation (write-capable only)
}

// SubagentResult is the output of a completed subagent.
type SubagentResult struct {
	ID          string
	Description string
	Response    string
	Usage       provider.Usage
	Turns       int
	Error       error
	Evidence    []agentloop.Evidence
	Status      SubagentStatus
	Duration    time.Duration
}

// StatusUpdate is sent via StatusCallback during subagent execution.
type StatusUpdate struct {
	ID          string
	Description string
	Status      SubagentStatus
	Turn        int
	MaxTurns    int
	TokensUsed  int
	Error       error
	Response    string // populated on StatusDone for TUI display
}

// StatusCallback receives real-time status updates from running subagents.
type StatusCallback func(StatusUpdate)
