package prompts

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/mistakeknot/Skaffen/pkg/style"
)

// Golden-file parity tests against Python prompts.py, following the pattern
// established by pkg/style/parity_test.go (sylveste-mg70): fixtures are
// generated by testdata/generate_fixtures.py running Auraken's
// build_system_prompt, and the Go output must be byte-identical.

// GoldenPromptFixtures mirrors the JSON structure from generate_fixtures.py.
// Exported-shape kept package-local; internal/auraken reuses the same file
// via its own copy of these structs.
type goldenPromptFixtures struct {
	Version   int              `json:"version"`
	Scenarios []goldenScenario `json:"scenarios"`
}

type goldenScenario struct {
	Name   string      `json:"name"`
	Input  goldenInput `json:"input"`
	Prompt string      `json:"prompt"`
}

type goldenInput struct {
	WorkingProfile   string          `json:"working_profile"`
	RecentTurns      []Turn          `json:"recent_turns"`
	StyleFingerprint json.RawMessage `json:"style_fingerprint"`
	ExploredDomains  []string        `json:"explored_domains"`
	KnownEntities    []Entity        `json:"known_entities"`
	InteractionCount int             `json:"interaction_count"`
	RelevantLenses   []Lens          `json:"relevant_lenses"`
	FeedbackEntities []Feedback      `json:"feedback_entities"`
	IsNewUser        bool            `json:"is_new_user"`
	CurrentMessage   string          `json:"current_message"`
}

func loadPromptFixtures(t *testing.T) goldenPromptFixtures {
	t.Helper()
	data, err := os.ReadFile("testdata/golden_fixtures.json")
	if err != nil {
		t.Fatalf("failed to read golden fixtures: %v", err)
	}
	var fixtures goldenPromptFixtures
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatalf("failed to parse golden fixtures: %v", err)
	}
	if len(fixtures.Scenarios) == 0 {
		t.Fatal("no scenarios in golden fixtures")
	}
	return fixtures
}

// PromptInputFromGolden converts a fixture input into a PromptInput.
func promptInputFromGolden(t *testing.T, in goldenInput) PromptInput {
	t.Helper()

	var fp *style.Fingerprint
	if len(in.StyleFingerprint) > 0 && string(in.StyleFingerprint) != "null" {
		fp = &style.Fingerprint{}
		if err := json.Unmarshal(in.StyleFingerprint, fp); err != nil {
			t.Fatalf("failed to parse fixture fingerprint: %v", err)
		}
	}

	var explored map[string]bool
	if in.ExploredDomains != nil {
		explored = make(map[string]bool, len(in.ExploredDomains))
		for _, d := range in.ExploredDomains {
			explored[d] = true
		}
	}

	return PromptInput{
		WorkingProfile:   in.WorkingProfile,
		RecentTurns:      in.RecentTurns,
		StyleFingerprint: fp,
		ExploredDomains:  explored,
		KnownEntities:    in.KnownEntities,
		InteractionCount: in.InteractionCount,
		RelevantLenses:   in.RelevantLenses,
		FeedbackEntities: in.FeedbackEntities,
		IsNewUser:        in.IsNewUser,
		CurrentMessage:   in.CurrentMessage,
	}
}

// diffStrings reports the first byte position where two strings diverge,
// with surrounding context, for readable parity failures.
func diffStrings(got, want string) string {
	limit := len(got)
	if len(want) < limit {
		limit = len(want)
	}
	i := 0
	for i < limit && got[i] == want[i] {
		i++
	}
	if i == limit && len(got) == len(want) {
		return "strings identical"
	}
	start := i - 60
	if start < 0 {
		start = 0
	}
	gotEnd := i + 60
	if gotEnd > len(got) {
		gotEnd = len(got)
	}
	wantEnd := i + 60
	if wantEnd > len(want) {
		wantEnd = len(want)
	}
	return fmt.Sprintf("first divergence at byte %d (got len %d, want len %d)\n  got:  %q\n  want: %q",
		i, len(got), len(want), got[start:gotEnd], want[start:wantEnd])
}

func TestGoldenSystemPromptParity(t *testing.T) {
	fixtures := loadPromptFixtures(t)

	for _, sc := range fixtures.Scenarios {
		t.Run(sc.Name, func(t *testing.T) {
			input := promptInputFromGolden(t, sc.Input)
			got := BuildSystemPrompt(DefaultConfig(), input)
			if got != sc.Prompt {
				t.Errorf("prompt mismatch with Python build_system_prompt:\n%s", diffStrings(got, sc.Prompt))
			}
		})
	}
}

// TestGoldenSectionParity verifies individual exported section builders
// against sections of the assembled Python prompt. The full-prompt test
// already guarantees parity; this pins the exported builders to the same
// content so provider-based assembly (internal/auraken) cannot drift.
func TestGoldenSectionParity(t *testing.T) {
	fixtures := loadPromptFixtures(t)

	for _, sc := range fixtures.Scenarios {
		t.Run(sc.Name, func(t *testing.T) {
			input := promptInputFromGolden(t, sc.Input)

			assembled := strings.NewReplacer(
				"{feedback_context}", BuildFeedbackContext(input.FeedbackEntities),
				"{lens_context}", BuildLensContext(input.RelevantLenses),
				"{profile_context}", BuildProfileContext(DefaultConfig(), input.WorkingProfile),
				"{steering_context}", BuildSteeringContext(input.ExploredDomains, input.KnownEntities, input.InteractionCount),
				"{style_context}", BuildStyleContext(input.StyleFingerprint, input.RecentTurns, input.CurrentMessage),
				"{session_context}", BuildSessionContext(input.RecentTurns),
			).Replace(DefaultSystemTemplate)
			assembled += BuildBootstrapContext(input.IsNewUser, input.InteractionCount)

			if assembled != sc.Prompt {
				t.Errorf("section-wise assembly mismatch:\n%s", diffStrings(assembled, sc.Prompt))
			}
		})
	}
}
